In [156]:
import pandas as pd
from sklearn.preprocessing import OneHotEncoder
import numpy as np
from google.colab import drive
from sklearn.preprocessing import LabelBinarizer
from sklearn.decomposition import PCA
from sklearn.preprocessing import StandardScaler

In [157]:
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [158]:
EmpleadosAttrition = pd.read_csv("/content/drive/MyDrive/diplomado/ingecaracteristicas/empleadosRETO.csv")
EmpleadosAttrition.head()

,Age,BusinessTravel,Department,DistanceFromHome,Education,EducationField,EmployeeCount,EmployeeNumber,EnvironmentSatisfaction,Gender,...,PercentSalaryHike,PerformanceRating,RelationshipSatisfaction,StandardHours,TotalWorkingYears,TrainingTimesLastYear,WorkLifeBalance,YearsInCurrentRole,YearsSinceLastPromotion,Attrition
0,50,Travel_Rarely,Research & Development,1 km,2,Medical,1,997,4,Male,...,22,4,3,80,32,1,2,4,1,No
1,36,Travel_Rarely,Research & Development,6 km,2,Medical,1,178,2,Male,...,20,4,4,80,7,0,3,2,0,No
2,21,Travel_Rarely,Sales,7 km,1,Marketing,1,1780,2,Male,...,13,3,2,80,1,3,3,0,1,Yes
3,52,Travel_Rarely,Research & Development,7 km,4,Life Sciences,1,1118,2,Male,...,19,3,4,80,18,4,3,6,4,No
4,33,Travel_Rarely,Research & Development,15 km,1,Medical,1,582,2,Male,...,12,3,4,80,15,2,4,6,7,Yes

In [159]:
EmpleadosAttrition= EmpleadosAttrition.drop(['EmployeeCount', 'Over18', 'StandardHours','EmployeeNumber'], axis=1)
EmpleadosAttrition.head()

,Age,BusinessTravel,Department,DistanceFromHome,Education,EducationField,EnvironmentSatisfaction,Gender,JobInvolvement,JobLevel,...,OverTime,PercentSalaryHike,PerformanceRating,RelationshipSatisfaction,TotalWorkingYears,TrainingTimesLastYear,WorkLifeBalance,YearsInCurrentRole,YearsSinceLastPromotion,Attrition
0,50,Travel_Rarely,Research & Development,1 km,2,Medical,4,Male,3,4,...,No,22,4,3,32,1,2,4,1,No
1,36,Travel_Rarely,Research & Development,6 km,2,Medical,2,Male,3,2,...,No,20,4,4,7,0,3,2,0,No
2,21,Travel_Rarely,Sales,7 km,1,Marketing,2,Male,3,1,...,No,13,3,2,1,3,3,0,1,Yes
3,52,Travel_Rarely,Research & Development,7 km,4,Life Sciences,2,Male,3,3,...,No,19,3,4,18,4,3,6,4,No
4,33,Travel_Rarely,Research & Development,15 km,1,Medical,2,Male,3,3,...,Yes,12,3,4,15,2,4,6,7,Yes

In [160]:
EmpleadosAttrition['HiringDate']

0      06/06/2013
1      12/25/2015
2       2/14/2017
3       7/29/2010
4      10/07/2011
          ...
395    05/09/2013
396    04/02/2016
397     1/21/2008
398     8/27/2018
399    02/08/2010
Name: HiringDate, Length: 400, dtype: object

In [161]:
EmpleadosAttrition['Year'] = EmpleadosAttrition['HiringDate'].str.split(pat='/').str[2].astype(int)
EmpleadosAttrition.head()

,Age,BusinessTravel,Department,DistanceFromHome,Education,EducationField,EnvironmentSatisfaction,Gender,JobInvolvement,JobLevel,...,PercentSalaryHike,PerformanceRating,RelationshipSatisfaction,TotalWorkingYears,TrainingTimesLastYear,WorkLifeBalance,YearsInCurrentRole,YearsSinceLastPromotion,Attrition,Year
0,50,Travel_Rarely,Research & Development,1 km,2,Medical,4,Male,3,4,...,22,4,3,32,1,2,4,1,No,2013
1,36,Travel_Rarely,Research & Development,6 km,2,Medical,2,Male,3,2,...,20,4,4,7,0,3,2,0,No,2015
2,21,Travel_Rarely,Sales,7 km,1,Marketing,2,Male,3,1,...,13,3,2,1,3,3,0,1,Yes,2017
3,52,Travel_Rarely,Research & Development,7 km,4,Life Sciences,2,Male,3,3,...,19,3,4,18,4,3,6,4,No,2010
4,33,Travel_Rarely,Research & Development,15 km,1,Medical,2,Male,3,3,...,12,3,4,15,2,4,6,7,Yes,2011

In [162]:
EmpleadosAttrition['YearsAtCompany '] = 2018-EmpleadosAttrition['Year']
EmpleadosAttrition.head()

,Age,BusinessTravel,Department,DistanceFromHome,Education,EducationField,EnvironmentSatisfaction,Gender,JobInvolvement,JobLevel,...,PerformanceRating,RelationshipSatisfaction,TotalWorkingYears,TrainingTimesLastYear,WorkLifeBalance,YearsInCurrentRole,YearsSinceLastPromotion,Attrition,Year,YearsAtCompany
0,50,Travel_Rarely,Research & Development,1 km,2,Medical,4,Male,3,4,...,4,3,32,1,2,4,1,No,2013,5
1,36,Travel_Rarely,Research & Development,6 km,2,Medical,2,Male,3,2,...,4,4,7,0,3,2,0,No,2015,3
2,21,Travel_Rarely,Sales,7 km,1,Marketing,2,Male,3,1,...,3,2,1,3,3,0,1,Yes,2017,1
3,52,Travel_Rarely,Research & Development,7 km,4,Life Sciences,2,Male,3,3,...,3,4,18,4,3,6,4,No,2010,8
4,33,Travel_Rarely,Research & Development,15 km,1,Medical,2,Male,3,3,...,3,4,15,2,4,6,7,Yes,2011,7

In [163]:
EmpleadosAttrition=EmpleadosAttrition.rename(columns={'DistanceFromHome':'DistanceFromHome_km'})
EmpleadosAttrition['DistanceFromHome_km']

0       1 km
1       6 km
2       7 km
3       7 km
4      15 km
       ...
395    14 km
396    20 km
397    11 km
398     4 km
399    14 km
Name: DistanceFromHome_km, Length: 400, dtype: object

In [164]:
EmpleadosAttrition['DistanceFromHome'] = EmpleadosAttrition['DistanceFromHome_km'].str.replace('km', '').astype(int)
EmpleadosAttrition['DistanceFromHome']

0       1
1       6
2       7
3       7
4      15
       ..
395    14
396    20
397    11
398     4
399    14
Name: DistanceFromHome, Length: 400, dtype: int64

In [165]:
EmpleadosAttrition= EmpleadosAttrition.drop(['Year', 'HiringDate', 'DistanceFromHome_km'], axis=1)
EmpleadosAttrition.head()

,Age,BusinessTravel,Department,Education,EducationField,EnvironmentSatisfaction,Gender,JobInvolvement,JobLevel,JobRole,...,PerformanceRating,RelationshipSatisfaction,TotalWorkingYears,TrainingTimesLastYear,WorkLifeBalance,YearsInCurrentRole,YearsSinceLastPromotion,Attrition,YearsAtCompany,DistanceFromHome
0,50,Travel_Rarely,Research & Development,2,Medical,4,Male,3,4,Research Director,...,4,3,32,1,2,4,1,No,5,1
1,36,Travel_Rarely,Research & Development,2,Medical,2,Male,3,2,Manufacturing Director,...,4,4,7,0,3,2,0,No,3,6
2,21,Travel_Rarely,Sales,1,Marketing,2,Male,3,1,Sales Representative,...,3,2,1,3,3,0,1,Yes,1,7
3,52,Travel_Rarely,Research & Development,4,Life Sciences,2,Male,3,3,Healthcare Representative,...,3,4,18,4,3,6,4,No,8,7
4,33,Travel_Rarely,Research & Development,1,Medical,2,Male,3,3,Manager,...,3,4,15,2,4,6,7,Yes,7,15

In [166]:
SueldoPromedioDepto = EmpleadosAttrition.groupby('Department')['MonthlyIncome'].mean().reset_index()
SueldoPromedioDepto.rename(columns={'MonthlyIncome': 'SueldoPromedio'}, inplace=True)
SueldoPromedioDepto.head()

               Department  SueldoPromedio
0         Human Resources     6239.888889
1  Research & Development     6804.149813
2                   Sales     7188.250000

In [167]:
EmpleadosAttrition['MonthlyIncome'] = (EmpleadosAttrition['MonthlyIncome'] - min(EmpleadosAttrition['MonthlyIncome'])) /(max(EmpleadosAttrition['MonthlyIncome']) - min(EmpleadosAttrition['MonthlyIncome']))
EmpleadosAttrition['MonthlyIncome']

0      0.864269
1      0.207340
2      0.088062
3      0.497574
4      0.664470
         ...
395    0.075248
396    0.187197
397    0.589327
398    0.121124
399    0.092122
Name: MonthlyIncome, Length: 400, dtype: float64

In [168]:

categoricas = ['BusinessTravel', 'Department', 'EducationField', 'JobRole', 'MaritalStatus', ]
lb = LabelBinarizer()
EmpleadosAttritiondummies = pd.get_dummies(EmpleadosAttrition[categoricas])
EmpleadosAttritiondummies = EmpleadosAttritiondummies.astype(int)
EmpleadosAttrition1 = EmpleadosAttrition.drop(categoricas, axis=1)
EmpleadosAttrition = pd.concat([EmpleadosAttrition1, EmpleadosAttritiondummies], axis=1)
EmpleadosAttrition['Attrition'] = lb.fit_transform(EmpleadosAttrition['Attrition'])
EmpleadosAttrition['Gender'] = lb.fit_transform(EmpleadosAttrition['Gender'])
EmpleadosAttrition['OverTime'] = lb.fit_transform(EmpleadosAttrition['OverTime'])
EmpleadosAttrition.head()

,Age,Education,EnvironmentSatisfaction,Gender,JobInvolvement,JobLevel,JobSatisfaction,MonthlyIncome,NumCompaniesWorked,OverTime,...,JobRole_Laboratory Technician,JobRole_Manager,JobRole_Manufacturing Director,JobRole_Research Director,JobRole_Research Scientist,JobRole_Sales Executive,JobRole_Sales Representative,MaritalStatus_Divorced,MaritalStatus_Married,MaritalStatus_Single
0,50,2,4,1,3,4,4,0.864269,9,0,...,0,0,0,1,0,0,0,1,0,0
1,36,2,2,1,3,2,2,0.207340,6,0,...,0,0,1,0,0,0,0,1,0,0
2,21,1,2,1,3,1,2,0.088062,1,0,...,0,0,0,0,0,0,1,0,0,1
3,52,4,2,1,3,3,2,0.497574,7,0,...,0,0,0,0,0,0,0,0,0,1
4,33,1,2,1,3,3,3,0.664470,7,1,...,0,1,0,0,0,0,0,0,1,0

In [169]:
EmpleadosAttrition.columns

Index(['Age', 'Education', 'EnvironmentSatisfaction', 'Gender',
       'JobInvolvement', 'JobLevel', 'JobSatisfaction', 'MonthlyIncome',
       'NumCompaniesWorked', 'OverTime', 'PercentSalaryHike',
       'PerformanceRating', 'RelationshipSatisfaction', 'TotalWorkingYears',
       'TrainingTimesLastYear', 'WorkLifeBalance', 'YearsInCurrentRole',
       'YearsSinceLastPromotion', 'Attrition', 'YearsAtCompany ',
       'DistanceFromHome', 'BusinessTravel_Non-Travel',
       'BusinessTravel_Travel_Frequently', 'BusinessTravel_Travel_Rarely',
       'Department_Human Resources', 'Department_Research & Development',
       'Department_Sales', 'EducationField_Human Resources',
       'EducationField_Life Sciences', 'EducationField_Marketing',
       'EducationField_Medical', 'EducationField_Other',
       'EducationField_Technical Degree', 'JobRole_Healthcare Representative',
       'JobRole_Human Resources', 'JobRole_Laboratory Technician',
       'JobRole_Manager', 'JobRole_Manufacturing Director',
       'JobRole_Research Director', 'JobRole_Research Scientist',
       'JobRole_Sales Executive', 'JobRole_Sales Representative',
       'MaritalStatus_Divorced', 'MaritalStatus_Married',
       'MaritalStatus_Single'],
      dtype='object')

In [170]:
correlaciones = {}#diccionario

for columna in EmpleadosAttrition.columns:
    if columna != 'Attrition':
        correlacion = EmpleadosAttrition['Attrition'].corr(EmpleadosAttrition[columna])
        correlaciones[columna] = abs(correlacion)
corr = pd.DataFrame(correlaciones.items(), columns=['Variable','Correlación'])
corr

                             Variable  Correlación
0                                 Age     0.212121
1                           Education     0.055531
2             EnvironmentSatisfaction     0.124327
3                              Gender     0.028839
4                      JobInvolvement     0.166785
5                            JobLevel     0.214266
6                     JobSatisfaction     0.164957
7                       MonthlyIncome     0.194936
8                  NumCompaniesWorked     0.009082
9                            OverTime     0.324777
10                  PercentSalaryHike     0.060880
11                  PerformanceRating     0.006471
12           RelationshipSatisfaction     0.030945
13                  TotalWorkingYears     0.213329
14              TrainingTimesLastYear     0.070884
15                    WorkLifeBalance     0.021723
16                 YearsInCurrentRole     0.203918
17            YearsSinceLastPromotion     0.069000
18                    YearsAtCompany      0.176001
19                   DistanceFromHome     0.052732
20          BusinessTravel_Non-Travel     0.100698
21   BusinessTravel_Travel_Frequently     0.035387
22       BusinessTravel_Travel_Rarely     0.042755
23         Department_Human Resources     0.023389
24  Department_Research & Development     0.072269
25                   Department_Sales     0.066116
26     EducationField_Human Resources     0.043404
27       EducationField_Life Sciences     0.027457
28           EducationField_Marketing     0.016768
29             EducationField_Medical     0.054144
30               EducationField_Other     0.004275
31    EducationField_Technical Degree     0.129104
32  JobRole_Healthcare Representative     0.103274
33            JobRole_Human Resources     0.032714
34      JobRole_Laboratory Technician     0.125264
35                    JobRole_Manager     0.089885
36     JobRole_Manufacturing Director     0.042404
37          JobRole_Research Director     0.116263
38         JobRole_Research Scientist     0.007977
39            JobRole_Sales Executive     0.003115
40       JobRole_Sales Representative     0.191294
41             MaritalStatus_Divorced     0.107869
42              MaritalStatus_Married     0.094734
43               MaritalStatus_Single     0.205849

In [171]:
menores = corr[corr['Correlación']< 0.1]['Variable'].tolist()
menores

['Education',
 'Gender',
 'NumCompaniesWorked',
 'PercentSalaryHike',
 'PerformanceRating',
 'RelationshipSatisfaction',
 'TrainingTimesLastYear',
 'WorkLifeBalance',
 'YearsSinceLastPromotion',
 'DistanceFromHome',
 'BusinessTravel_Travel_Frequently',
 'BusinessTravel_Travel_Rarely',
 'Department_Human Resources',
 'Department_Research & Development',
 'Department_Sales',
 'EducationField_Human Resources',
 'EducationField_Life Sciences',
 'EducationField_Marketing',
 'EducationField_Medical',
 'EducationField_Other',
 'JobRole_Human Resources',
 'JobRole_Manager',
 'JobRole_Manufacturing Director',
 'JobRole_Research Scientist',
 'JobRole_Sales Executive',
 'MaritalStatus_Married']

In [172]:
EmpleadosAttritionFinal=EmpleadosAttrition.drop(menores, axis=1)
EmpleadosAttritionFinal.head()

,Age,EnvironmentSatisfaction,JobInvolvement,JobLevel,JobSatisfaction,MonthlyIncome,OverTime,TotalWorkingYears,YearsInCurrentRole,Attrition,YearsAtCompany,BusinessTravel_Non-Travel,EducationField_Technical Degree,JobRole_Healthcare Representative,JobRole_Laboratory Technician,JobRole_Research Director,JobRole_Sales Representative,MaritalStatus_Divorced,MaritalStatus_Single
0,50,4,3,4,4,0.864269,0,32,4,0,5,0,0,0,0,1,0,1,0
1,36,2,3,2,2,0.207340,0,7,2,0,3,0,0,0,0,0,0,1,0
2,21,2,3,1,2,0.088062,0,1,0,1,1,0,0,0,0,0,1,0,1
3,52,2,3,3,2,0.497574,0,18,6,0,8,0,0,1,0,0,0,0,1
4,33,2,3,3,3,0.664470,1,15,6,1,7,0,0,0,0,0,0,0,0

In [173]:

pca = PCA()
EmpleadosAttritionPCA = pca.fit_transform( EmpleadosAttritionFinal)
print(EmpleadosAttritionPCA[:, 0])

[ 20.25273406  -6.38233644 -21.51387114  13.82728483  -1.43453461
  21.80590348 -18.21185     -7.06990543   5.66643182 -11.0159337
  -3.99216663  16.93730139 -10.10882435   3.94893849  15.56677331
  -0.34454161  -6.76389191   3.90926734  11.91836611  20.95811509
  -4.92899365   4.73780511  -7.03638643 -20.44667531   4.90990681
  -1.17315421 -22.20094853 -10.98220644  17.99480977   1.33958024
  -6.29562814  -0.85396957  20.93624179  -4.16186667  -5.67412044
  12.66383414   1.6271729   25.06852411  -5.26474168  -0.68488961
  12.0060047   -5.01064505   5.81655272  -7.70498423  -4.64542778
  19.48726268  -3.3988706    6.07303713   3.54055295  -7.38013655
  -4.2800592   10.705117    13.07817172  -9.45537865   0.55969692
 -12.10730731  -4.08562348  -7.76608881  12.3332622    2.28625439
   2.71976496  -4.11679467   4.88060744 -13.5317583    3.81286606
  -2.56712732  -0.50585604  -2.09184004   0.92588437  -4.85143118
   3.28747968  -5.18233106   0.59852465   0.67866662 -10.55075395
 -23.19566266 -10.02817969   4.14838632   3.78137187 -16.02282941
  -7.02795762  13.84779536  -3.79863765  -2.50959291 -20.82817731
  -9.53955306  14.04782745   6.31181986  -4.61907354   7.88561949
   0.82537968  -3.33084046   4.82597804  -3.70837111  -7.01718787
  -2.70449556  -6.85010787   3.80265946  -2.05702395  -3.99841532
  -6.58978943  -9.97208358  -5.76671732  -3.94720137   2.50912608
  11.29984733  -0.71742396  -8.53970759  25.84128438 -12.87605113
 -15.33769308 -10.88721237  27.64376608   1.49278738  12.91621369
  11.3128817   -2.11368563  -0.72162713  15.20784145  15.67402983
  23.21859451  -4.69316797 -20.14232193   8.37154302  -6.556066
  -5.21153677  -4.89266742  10.09163544  18.83493047  -4.79367441
  -5.65028815  11.27257349  -7.09857438  -0.75907366  -3.8855142
   8.75763018  11.69320534   7.4761238    1.27042331  27.77110458
   6.49119522  -1.58190021  16.90600391  32.47772454  -0.58535151
  23.13385277  -4.77940354   1.14826121 -19.31039264  -7.87921371
  -7.01674416  18.17681755   1.94366337   3.83395705   2.24384743
 -19.44812918  -8.48207756   2.22098357  -8.09552228  -5.20144109
  23.83734371   7.80447728   2.00406738  -9.29116415  -6.33908748
  -6.04754748  18.533889   -12.64784916   2.24593135  24.70840497
  12.94678411  -5.75595036  12.05930115  15.55974353 -14.48569848
   0.77696129   5.14910606  15.26674506 -11.62874232  17.53318146
  -8.93968985  16.10288611  -3.25133785  -5.03005904  13.65793943
  -8.16951992  15.32822451 -22.87147844  -5.09894416   1.1959769
  -4.59308162   4.38289171  15.616679    -6.44350376  13.77916611
  -2.626574    -4.50189524  16.35162387  18.77547724  -6.46933792
   0.44810804  -7.30067785   0.83970236  -6.29436123 -12.46555813
 -10.49104331 -15.59327218   1.8675631    7.09134017  -6.76615035
  -5.54325115  24.29987718  -2.09187608 -15.0538053  -15.33448695
  13.29317863   0.45576072   5.78839755   6.28501629 -16.01123138
   6.18763744 -11.05687697  14.49065013  12.64635521 -22.20541057
  -1.94409741  -1.04034761 -13.48709219   0.22594511  -4.67496537
  -8.444488    -4.46183275  -1.09858557  14.09329361   3.79950609
  -1.0882179   -1.79721712   7.07282313  -9.16265466   1.07403033
  -8.99170055   2.70371916 -10.9831      -2.58302578  15.89970304
  11.86859185  29.15648113  12.93902629  -1.13186541  -4.37789132
 -14.77444458   5.03304845  -8.421057    -6.69634355  16.66659243
  10.02580146 -20.9465233   -7.4288208   -8.03279751   4.57641379
  19.02119674 -12.97347256   2.45484296  26.05129684  -1.56869589
  -0.23028407   8.30325696 -20.12670581   8.62157031 -13.80667938
  24.95393304  13.35949654  -7.94098983  -9.3876819    5.47741159
 -13.30884676  -3.2615998   -0.16129837 -13.11352837   1.98745484
  -2.09035622  -1.20348588  -1.87477777   0.39679386  28.58999869
  15.76752328  -3.2201853  -10.36079729   6.6722095    6.28024017
  -5.56344072  -5.53745357 -14.46991654   8.65045965 -22.20150638
   0.92304802 -22.88687563 -12.7464112  -13.97385793  -2.93531703
  -1.26251836  13.99332199  23.0302587   11.0104331  -15.32810039
  -2.03750174   0.86118208 -17.6755576  -19.32255567   1.63637692
  12.70475971 -10.59294499  -0.908425     2.86928192   2.28484243
   5.19979491   0.13189484  -3.41329926   4.83923322   5.34558575
  -5.13804997  -5.14751047  15.69601962   0.80704475  -7.55845119
  -8.46111141  -5.4527556  -10.57639192  -2.73362016  11.46653065
  -9.40694764  -5.69450371 -12.58016767  -4.00318944 -14.76465307
  12.49924817   2.90550419  -2.40813237  -8.94553352  20.66983066
  -3.91354466  -0.63384426  -2.25330533  -1.34345972   6.57372524
  -1.10567278  13.13391877 -24.51912316  -7.39363489  -7.04953583
 -11.43356585  -2.78252006  27.29870689  -6.52867404  -4.44207387
  -8.61674113  -0.39995484   1.11161674  12.02080479   9.68096323
  -6.56169952  13.95349006   4.42181273 -15.18826702 -14.58572529
   9.52857923 -10.57659745   8.73210367  13.77613146  -5.78185727
  11.38970297  -1.15146344  -8.96544702  -8.77779169  -3.5039107
   1.51947922 -13.46650666 -12.21394028  16.43580378 -16.65094971
  -0.73987934  -7.37418694 -10.16436036   7.29991832  -7.65218794
  -1.89226519  -3.50518634  -2.39438149  -8.16844321   2.61535302
  -4.77387307  -9.92132017   6.46998954  13.58613162 -10.16561356
  -6.97747545 -12.04308951  -0.64274909  -6.31378492  -5.58942547]

In [174]:
#varianzaex = pca.explained_variance_
varianzaexra = pca.explained_variance_ratio_
#puntos = pca.transform(X)
varianzafin = np.cumsum(varianzaexra)
num_componentes = np.argmax(varianzafin >= 0.8) + 1
componentes_df = pd.DataFrame(EmpleadosAttritionPCA[:, :num_componentes], columns=[f'C{i}' for i in range(num_componentes)])
EmpleadosAttritionFinal = EmpleadosAttritionFinal.assign(**componentes_df)
EmpleadosAttritionFinal.head()

,Age,EnvironmentSatisfaction,JobInvolvement,JobLevel,JobSatisfaction,MonthlyIncome,OverTime,TotalWorkingYears,YearsInCurrentRole,Attrition,...,BusinessTravel_Non-Travel,EducationField_Technical Degree,JobRole_Healthcare Representative,JobRole_Laboratory Technician,JobRole_Research Director,JobRole_Sales Representative,MaritalStatus_Divorced,MaritalStatus_Single,C0,C1
0,50,4,3,4,4,0.864269,0,32,4,0,...,0,0,0,0,1,0,1,0,20.252734,-4.207118
1,36,2,3,2,2,0.207340,0,7,2,0,...,0,0,0,0,0,0,1,0,-6.382336,-3.690989
2,21,2,3,1,2,0.088062,0,1,0,1,...,0,0,0,0,0,1,0,1,-21.513871,1.744893
3,52,2,3,3,2,0.497574,0,18,6,0,...,0,0,1,0,0,0,0,1,13.827285,-5.843714
4,33,2,3,3,3,0.664470,1,15,6,1,...,0,0,0,0,0,0,0,0,-1.434535,4.144322

In [175]:
varianzaexra

array([6.34078438e-01, 2.41404414e-01, 7.88214347e-02, 2.10120695e-02,
       6.51405509e-03, 6.44067248e-03, 2.99320426e-03, 2.81623939e-03,
       1.38369811e-03, 1.10177607e-03, 6.76796300e-04, 6.37612180e-04,
       5.03612681e-04, 4.46229979e-04, 3.92356986e-04, 2.83571386e-04,
       2.51083610e-04, 2.16940284e-04, 2.57950205e-05])

In [177]:
EmpleadosAttritionFinal.to_csv("/content/drive/MyDrive/diplomado/ingecaracteristicas/EmpleadosAttritionFinal.csv")